import type { Product, User, Sale } from "./types";

export const seedProducts: Product[] = [
  // Suplementos — marcas reales del mercado colombiano
  {
    id: "p1",
    sku: "MT-CR-300",
    name: "Cell-Tech Creactor 300g",
    brand: "MuscleTech",
    category: "suplementos",
    price: 189000,
    cost: 128000,
    stock: 14,
    minStock: 6,
    description: "Creatina HCL + ácido libre, sabor frutos rojos.",
  },
  {
    id: "p2",
    sku: "MT-WP-2270",
    name: "Nitro-Tech Whey Gold 5lb",
    brand: "MuscleTech",
    category: "suplementos",
    price: 339000,
    cost: 248000,
    stock: 9,
    minStock: 4,
    description: "Proteína aislada 24g por servida, chocolate.",
  },
  {
    id: "p3",
    sku: "IRN-CR-500",
    name: "Creatine Monohydrate 500g",
    brand: "Iron Nutrition",
    category: "suplementos",
    price: 145000,
    cost: 92000,
    stock: 22,
    minStock: 8,
    description: "Creatina monohidratada micronizada sin sabor.",
  },
  {
    id: "p4",
    sku: "IRN-WP-2270",
    name: "Iron Whey 5lb",
    brand: "Iron Nutrition",
    category: "suplementos",
    price: 285000,
    cost: 196000,
    stock: 3,
    minStock: 5,
    description: "Concentrado de suero, vainilla francesa.",
  },
  {
    id: "p5",
    sku: "SMT-PR-2000",
    name: "Smart Protein Isolate 2kg",
    brand: "Smart",
    category: "suplementos",
    price: 312000,
    cost: 215000,
    stock: 7,
    minStock: 4,
    description: "Aislado de suero 27g, fresa.",
  },
  {
    id: "p6",
    sku: "SMT-CR-300",
    name: "Smart Creatina 300g",
    brand: "Smart",
    category: "suplementos",
    price: 119000,
    cost: 76000,
    stock: 0,
    minStock: 6,
    description: "Creatina monohidratada premium nacional.",
  },
  {
    id: "p7",
    sku: "MT-PRE-30",
    name: "VaporX5 Next Gen Pre-workout",
    brand: "MuscleTech",
    category: "suplementos",
    price: 159000,
    cost: 102000,
    stock: 11,
    minStock: 5,
    description: "Pre-entreno con cafeína 200mg, beta-alanina.",
  },
  {
    id: "p8",
    sku: "IRN-BCAA-400",
    name: "BCAA 2:1:1 — 400g",
    brand: "Iron Nutrition",
    category: "suplementos",
    price: 98000,
    cost: 61000,
    stock: 18,
    minStock: 6,
    description: "Aminoácidos ramificados con electrolitos.",
  },
  // Tecnología
  {
    id: "t1",
    sku: "TECH-AUR-01",
    name: "Audífonos Inalámbricos Pro",
    brand: "Sony",
    category: "tecnologia",
    price: 245000,
    cost: 168000,
    stock: 6,
    minStock: 3,
    description: "Bluetooth 5.3, batería 30h, ideal para entreno.",
  },
  {
    id: "t2",
    sku: "TECH-SW-02",
    name: "Smartwatch Fitness Tracker",
    brand: "Xiaomi",
    category: "tecnologia",
    price: 189000,
    cost: 121000,
    stock: 10,
    minStock: 4,
    description: "HR, SpO2, GPS asistido, IP68.",
  },
  {
    id: "t3",
    sku: "TECH-PWR-03",
    name: "Power Bank 20.000mAh",
    brand: "Anker",
    category: "tecnologia",
    price: 145000,
    cost: 92000,
    stock: 2,
    minStock: 4,
    description: "Carga rápida PD 22.5W, doble salida.",
  },
  {
    id: "t4",
    sku: "TECH-BTL-04",
    name: "Botella Inteligente Hydra",
    brand: "HidrateSpark",
    category: "tecnologia",
    price: 98000,
    cost: 58000,
    stock: 15,
    minStock: 6,
    description: "Recordatorios LED de hidratación, 750ml.",
  },
  // Accesorios
  {
    id: "a1",
    sku: "ACC-SHK-01",
    name: "Shaker Training School 700ml",
    brand: "Training School",
    category: "accesorios",
    price: 25000,
    cost: 9000,
    stock: 42,
    minStock: 10,
    description: "Branded shaker con compartimento.",
  },
  {
    id: "a2",
    sku: "ACC-GLV-01",
    name: "Guantes de entrenamiento Pro",
    brand: "RDX",
    category: "accesorios",
    price: 75000,
    cost: 39000,
    stock: 8,
    minStock: 4,
    description: "Cuero sintético, palma reforzada.",
  },
];

export const seedUsers: User[] = [
  {
    id: "u1",
    name: "Camilo Restrepo",
    role: "admin",
    email: "camilo@trainingschool.co",
    password: "Admin2026*",
    active: true,
  },
  {
    id: "u2",
    name: "Andrea Gómez",
    role: "cajero",
    email: "andrea@trainingschool.co",
    password: "Cajero2026*",
    active: true,
  },
  {
    id: "u3",
    name: "Sebastián Pérez",
    role: "cajero",
    email: "sebastian@trainingschool.co",
    password: "Cajero2026*",
    active: true,
  },
  {
    id: "u4",
    name: "Laura Marín",
    role: "entrenador",
    email: "laura@trainingschool.co",
    password: "Coach2026*",
    active: true,
  },
  {
    id: "u5",
    name: "Daniel Ortiz",
    role: "entrenador",
    email: "daniel@trainingschool.co",
    password: "Coach2026*",
    active: false,
  },
];

export const DEMO_CREDENTIALS = [
  {
    role: "admin" as const,
    label: "Administrador",
    description: "Control total — equipo, inventario y configuración",
    name: "Camilo Restrepo",
    email: "camilo@trainingschool.co",
    password: "Admin2026*",
    accent: "from-blue-500 to-indigo-700",
  },
  {
    role: "cajero" as const,
    label: "Cajero",
    description: "Punto de venta + ventas + lectura de inventario",
    name: "Andrea Gómez",
    email: "andrea@trainingschool.co",
    password: "Cajero2026*",
    accent: "from-cyan-400 to-blue-600",
  },
  {
    role: "entrenador" as const,
    label: "Entrenador",
    description: "Lectura de inventario + asesor IA Coach Pro",
    name: "Laura Marín",
    email: "laura@trainingschool.co",
    password: "Coach2026*",
    accent: "from-fuchsia-400 to-purple-600",
  },
];

const now = Date.now();
const day = 86400000;

const buildSale = (
  i: number,
  daysAgo: number,
  items: { id: string; qty: number }[],
  cashier: User,
  method: Sale["paymentMethod"],
  customer?: string
): Sale => {
  const lineItems = items.map(({ id, qty }) => {
    const p = seedProducts.find((x) => x.id === id)!;
    return { productId: id, name: p.name, qty, unitPrice: p.price };
  });
  return {
    id: `s${i}`,
    date: new Date(now - daysAgo * day - i * 1800000).toISOString(),
    items: lineItems,
    total: lineItems.reduce((a, b) => a + b.qty * b.unitPrice, 0),
    cashierId: cashier.id,
    cashierName: cashier.name,
    paymentMethod: method,
    customerName: customer,
  };
};

const c1 = seedUsers[1];
const c2 = seedUsers[2];

export const seedSales: Sale[] = [
  buildSale(1, 0, [{ id: "p2", qty: 1 }, { id: "a1", qty: 1 }], c1, "tarjeta", "Juan Salazar"),
  buildSale(2, 0, [{ id: "p3", qty: 2 }], c2, "nequi"),
  buildSale(3, 0, [{ id: "p1", qty: 1 }, { id: "p7", qty: 1 }], c1, "efectivo", "María López"),
  buildSale(4, 1, [{ id: "p5", qty: 1 }], c2, "tarjeta"),
  buildSale(5, 1, [{ id: "t2", qty: 1 }, { id: "t4", qty: 1 }], c1, "tarjeta", "Carlos Henao"),
  buildSale(6, 2, [{ id: "p2", qty: 1 }, { id: "p3", qty: 1 }], c2, "daviplata"),
  buildSale(7, 2, [{ id: "p8", qty: 2 }], c1, "efectivo"),
  buildSale(8, 3, [{ id: "p1", qty: 1 }], c2, "nequi", "Sofía Quintero"),
  buildSale(9, 3, [{ id: "t1", qty: 1 }], c1, "tarjeta"),
  buildSale(10, 4, [{ id: "p4", qty: 1 }, { id: "a1", qty: 2 }], c2, "efectivo"),
  buildSale(11, 4, [{ id: "p7", qty: 1 }], c1, "tarjeta"),
  buildSale(12, 5, [{ id: "p3", qty: 1 }, { id: "p8", qty: 1 }], c2, "nequi", "Andrés Cano"),
  buildSale(13, 5, [{ id: "t3", qty: 1 }], c1, "tarjeta"),
  buildSale(14, 6, [{ id: "p2", qty: 1 }], c2, "tarjeta", "Felipe Arias"),
  buildSale(15, 6, [{ id: "a2", qty: 1 }, { id: "p1", qty: 1 }], c1, "efectivo"),
];
